### ISSUE TITLE
Missing hashIdNode UUID values

### ISSUE THREAD

**Issue by blairjordan** [chainpoint/chainpoint-js#2]
`chainpoint-js` version 0.4.4:

Calling `getProofs` returns:
```
UnhandledPromiseRejectionWarning: Error: some proof handles contain invalid hashIdNode UUID values
```

The proof handles returned from `submitHashes` do not contain the `hashIdNode`.

(An older version: 0.0.1 of `chainpoint-client` runs fine in RunKit)

**Comment by jacohend** [comment]
Hi @blairjordan , thanks for reporting this. As you can see [here](https://github.com/chainpoint/chainpoint-js/blob/master/lib/get.js#L58), we are actually using proofId rather than hashIdNode. We'll be sure to update this error message to reflect this.

Please be advised that this client is for the new Chainpoint Testnet, which is currently only anchoring to Bitcoin Testnet. To use the testnet, you'll want to use a new Gateway IP of `['http://3.136.178.15']` as the `uris` argument to these methods.  

To use legacy `chainpoint-services` to anchor to Bitcoin, you'll want to continue using `chainpoint-client-js` with the older version.

**Comment by blairjordan** [comment]
Thanks for replying @jacohend
The hashes are being submitted now, and I am now seeing the populated `proofId` in the proof handles, however using these with the `getProofs` function returns:
```
    code: 'InvalidArgument',
    message: 'invalid request, at least one proof id required',
    anchorsComplete: []
```

**Comment by jacohend** [comment]
Thanks Blair- we've made sure to publish the latest changes to npm. Can you
test and let us know if that solves your issue?

**Comment by blairjordan** [comment]
This did the trick! Thanks @jacohend

Code:
```
    const encoded = encode(data);
    const hash = createHash('sha256').update(encoded).digest('hex');
    let hashes = [ hash ]
    const proofHandles = await submitHashes(hashes, 
      [ 'http://3.136.178.15' ] // Testnet
    );
    
    console.log('Sleeping 20 seconds to wait for proofs to generate...');
    await new Promise(resolve => setTimeout(resolve, 12000));
    console.log(proofHandles);

    let proofs = await getProofs(proofHandles);
    console.log('Proof Objects: Expand objects below to inspect.')
    console.log(proofs)
```
Output:
```
Sleeping 20 seconds to wait for proofs to generate...
[
  {
    uri: 'http://3.136.178.15',
    hash: '3babca4efcb3594633e32b52f0457b80a0b4c58c9bed6eafc2e2f58b0392670f',
    proofId: 'c0ac5f50-64e2-11ea-ab28-01ccf1fff111',
    groupId: 'c0c84bc0-64e2-11ea-8035-0b4e07171c64'
  }
]
Proof Objects: Expand objects below to inspect.
[
  {
    proofId: 'c0ac5f50-64e2-11ea-ab28-01ccf1fff111',
    proof: null,
    anchorsComplete: []
  }
]
```
