### ISSUE TITLE
Merkle proof in v4

### ISSUE THREAD

**Issue by JohnDeey** [chainpoint/chainpoint-js#8]
Seems like the complete merkle proof that we could retrieve from the calendar server is no longer part of the validation schema in v4.
How can I get the proof that used to be under  ` "branches": []` ?

**Comment by katelynsills** [comment]
I had the same question for v5. I found [this article](https://runkit.com/tierion/verify-a-chainpoint-proof-directly-using-bitcoin), but it doesn't actually seem to provide a proof - how is the submitted hash connected to the calendar merkle root?

**Comment by jacohend** [comment]
Hi @JohnDeey and @katelynsills,

We dropped the branches key from the validation schema because the content there is dynamic and so doesn't make sense to try and validate. 

The full merkle proof can be obtained from the chainpoint-js getProof call or [directly from a Gateway](https://github.com/chainpoint/chainpoint-gateway/wiki/Gateway-HTTP-API). Here's a [sample proof](https://github.com/chainpoint/chainpoint-parse/blob/master/test/data/chainpoint-proof-v5.chp.json) obtained from getProof. All the proof content is now recursively nested under the `branches` key as of v4 and v5. The actual evaluation is performed in here:  https://github.com/chainpoint/chainpoint-parse/blob/master/index.js so you can see how the hash is connected to both blockchains. 

Please let me know if you have any other questions.

**Comment by katelynsills** [comment]
Thanks for the quick response, @jacohend! I'm still a little confused because I'm not able to get something that looks like the sample proof (JSON-LD with `ops`) from the chainpoint-js package.

First, it doesn't look like there's a way to specify JSON-LD as the format in `getProofs`. It [only returns the Base64 encoded binary form](https://github.com/chainpoint/chainpoint-js/blob/1bf369cdd79163198471cd0d2b2725de58528998/lib/get.js#L28). 

Second, if I parse the binary form using `chainpoint-parse`, I get a result that doesn't have any `ops` [Edit: Re-reading the [documentation](https://github.com/chainpoint/chainpoint-parse), I see that the expected output doesn't have the ops, but then I am not sure how to get the original proof from the binary form]:

```
{
  "hash": "d46edb3bf95b0a0fc5c86e019dd1d92420d390f041576951366b8dcb78f04cc9",
  "proof_id": "01GRSAJ8JK6RWDNX93FZD7FGN1",
  "hash_received": "2023-02-08T20:13:10Z",
  "branches": [
    {
      "label": "aggregator",
      "anchors": [],
      "branches": [
        {
          "label": "cal_anchor_branch",
          "anchors": [
            {
              "type": "cal",
              "anchor_id": "d67b4067ccb3a798e9c56c5ff6edfeab8a7afe9bf21bd97b1d1c98da7e519987",
              "uris": [
                "http://18.220.31.138/calendar/d67b4067ccb3a798e9c56c5ff6edfeab8a7afe9bf21bd97b1d1c98da7e519987/data"
              ],
              "expected_value": "e63cbdef22af6c9e06e7159113cd4e6ee0c1ebed28b7934405c2caf342de19b7"
            }
          ]
        }
      ]
    }
  ]
}
```

Whereas I can request JSON-LD format from a Gateway and I get the `ops` Merkle tree proof: 

```
curl -X GET http://18.224.185.143/proofs/01GRSAJ8JK6RWDNX93FZD7FGN1 -H 'Accept: application/vnd.chainpoint.ld+json' | jq
```

```
[
  {
    "proof_id": "01GRSAJ8JK6RWDNX93FZD7FGN1",
    "proof": {
      "@context": "https://w3id.org/chainpoint/v5",
      "branches": [
        {
          "label": "aggregator",
          "ops": [
            {
              "r": "a7639f7eaa2dcf74c788ce5c2513a534dddddb5effa26ec519a8a5033d460f80"
            },
            {
              "op": "sha-256"
            }
          ],
          "branches": [
            {
              "label": "cal_anchor_branch",
              "ops": [
                {
                  "l": "drand:2681873:b4896337533a60349c8a6297a3c323c66d8d3c1b60470d09b58ee7d1dd679951"
                },
                {
                  "op": "sha-256"
                },
                {
                  "r": "f6807e53d0d38923c1fe18218cf8ac3dcfa1b93aba1c649e2f4541c9803c50e8"
                },
                {
                  "op": "sha-256"
                },
                {
                  "anchors": [
                    {
                      "anchor_id": "d67b4067ccb3a798e9c56c5ff6edfeab8a7afe9bf21bd97b1d1c98da7e519987",
                      "type": "cal",
                      "uris": [
                        "http://18.220.31.138/calendar/d67b4067ccb3a798e9c56c5ff6edfeab8a7afe9bf21bd97b1d1c98da7e519987/data"
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ],
      "hash": "d46edb3bf95b0a0fc5c86e019dd1d92420d390f041576951366b8dcb78f04cc9",
      "hash_received": "2023-02-08T20:13:10Z",
      "proof_id": "01GRSAJ8JK6RWDNX93FZD7FGN1",
      "type": "Chainpoint"
    }
  }
]
```

Am I doing something wrong in my usage of chainpoint-js, or does it not give the merkle tree proof? Thanks!

**Comment by jacohend** [comment]
Hi @katelynsills,

Yes you're correct, you should getProof, Parse, then Verify. All the info, including the ops, are there in the b64 proof but parsing will get you want you want with operations in ~140 second (calendar) and 5400 second (bitcoin) delays. This is owing to the asynchronous nature of the chains. 

You have an empty aggregation stage because you were the sole user of that public gateway in that calendar submission epoch (every minute). So no left/right tree ops needed, because it's not a tree. If you look at the [aggregator code](https://github.com/chainpoint/chainpoint-core/blob/master/aggregator/aggregator.go#L163), you see it's just a hash in this case. 

Now you'll need to wait 90 minutes, then retrieve again. Chainpoint-connector might be able to help you here. Or you could just thread sleep if your needs are only periodic. We cache for six hours after bitcoin completes the final proof. 
 
This aggregation stages explanation may also help: https://github.com/chainpoint/chainpoint-start#chainpoint-network

Great questions- this is helping us understand what the ecosystem looks like from the outside after plenty of legacy iterations. Feel free to send to jacob at tierion dot com directly if you want more precise explanations or need more direct support.

**Comment by jacohend** [comment]
Here's a standard snippet that we use to test:

```
const chp = require('chainpoint-js')
const chainpointParse = require('chainpoint-parse')
const cpb = require('chainpoint-binary')


async function runIt() {
    try {
        // A few sample SHA-256 proofs to anchor
        let hashes = [
            '1d2a9e92b561440e8d27a21eed114f7018105db00262af7d7087f7dea9986b0a',
            '2d2a9e92b561440e8d27a21eed114f7018105db00262af7d7087f7dea9986b0a',
            '3d2a9e92b561440e8d27a21eed114f7018105db00262af7d7087f7dea9986b0a'
        ]

        let uris = []
        // Submit each hash to selected Nodes
        let proofHandles = await chp.submitHashes(hashes, uris)
        console.log('Submitted Proof Objects: Expand objects below to inspect.')
        console.log(JSON.stringify(proofHandles))
        // Wait for Calendar proofs to be available
        console.log('Sleeping 200 seconds to wait for proofs to generate...')
        await new Promise(resolve => setTimeout(resolve, 200000))
        // Retrieve a Calendar proof for each hash that was submitted
        let proofs = await chp.getProofs(proofHandles)
        console.log('Proof Objects: Expand objects below to inspect.')
        proofs.forEach(proof => {
            // Valid proof in JS Object, Buffer, Hex String, or Base64 String form
            let chainpointProofObject = proof.proof

            try {
                proofObj = cpb.binaryToObjectSync(chainpointProofObject)
                let proofJSON = JSON.stringify(proofObj, null, 2)
                console.log(proofJSON)
                let result = chainpointParse.parse(chainpointProofObject)
                console.log(JSON.stringify(result))
            } catch (error) {
                console.error(`An error has occurred: ${error.message}`)
            }
        });

        // some gateways in the worst case will cache a non response for another epoch...
        await new Promise(resolve => setTimeout(resolve, 200000))
        
        // Verify every anchor in every Calendar proof
        let verifiedProofs = await chp.verifyProofs(proofs)
        console.log('Verified Proof Objects: Expand objects below to inspect.')
        console.log(verifiedProofs)

        // Wait 90 minutes and call getProofs again on these handles to retrieve bitcoin proofs
        
    }catch(error){
        console.log(`error: ${error.message}`)
        console.log(`stack: ${error.stack}`)
    }
}
runIt()
```

**Comment by katelynsills** [comment]
Thanks, @jacohend. It looks like `cpb.binaryToObjectSync` was the function I was looking for.

**Comment by jacohend** [comment]
We'll be sure to modify the docs to better reflect that. Thanks for taking the time to comment!
